### PR TITLE
Option to disable writing mda to database

### PR DESCRIPTION
**Pull request by hoewer**
PR as discussed last week.
I'm not sure wether the error routine directly behind my change still works as expected when writing 2 times to the DB.

### CODE REVIEW

**Comment by PF4Public** [comment]
Thanks! I'll review your PR on a weekend or maybe a little bit later.

**Comment by PF4Public** [comment]
Thanks! I'll review your PR on a weekend or maybe a little bit later.

There are little nitpicks up front:
* It would be better to have this option disabled by default in order to avoid surprises for existing installations
* The description is a little bit confusing and contradictory: 
    * _fetchmail_mda\_**editable**_ ←→ _Option to **disable writing**_
    * _fetchmail_mda\_**editable**_ ←→ _This **prevents** existing entries from **being overwritten**_

**Comment by hoewer** [comment]
I've named the option "`fetchmail_mda_editable`" based on your suggestion. If it's set to `true` (my default) existing installations aren't affected in any way. Mda should be written as before. But I can unserstand why that's confusing. In fact the "Option to disable..." ist chosen if it is set to `false`.
What would you think about turning it the other way round: Titeling the option "`fetchmail_mda_locked`" and swapping `true` and `false`...

**Comment by PF4Public** [comment]
Wait wait wait. I understood it that you suggested to implement the ability for end-user (I mean, mailbox user, not someone, who is hosting roundcube) to change the contents of this field. In that case there should be an if-else case which renders or does not render the input box for `mda` for the user and similarly if-else case to persist that value into the database.

Did I get it wrong?

**Comment by hoewer** [comment]
Originally I actually thought it would be a good idea to let the "end user" maintain the mda via the GUI. However, when you suggested to introduce a new variable 'fetchmail_mda_editable', I realized that my initial approach (extending the GUI) might lead to a lot confusion, especially since my use case doesn't seem to be very common.
Typical (Mailbox-)users won't care about the mda, they usually don't even know which mda is available on the installation.

So I added the new variable to 'config.inc.php', which the admin-user can edit, but doesn't have to. It is important that existing installations are not affected. This is what I tried to achieve with my current approach:
Currently the mda is overwritten when editing a mailaccount via GUI - either with the 'mda' variable or with an empty string. My new variable is aimed prevent this: existing entries remain untouched.

Maintenance of multiple/different mda-strings in any case has to be done outside of the plugin, either via postfixadmin or directly on the database.

Have I expressed my idea clearly? Do you have any additional questions?

**Comment by PF4Public** [comment]
Now I see what you mean, thank you for explanations.

In this case we do not need any other variables at all. It would be fairly straightforward to do a simple if/else case with 2 DB queries for whether `fetchmail_mda` is empty or not to either submit mda or simply exclude it. This logic should be of-course reflected in the description of `fetchmail_mda` option.

I apologize for my replies being somewhat delayed.

**Comment by hoewer** [comment]
There's nothing to apologize for. My guess is that most contributors invest their spare time here. So I'm happy that you care for this plugin; response time is really unimportant.
Using `fetchmail_mda` seems in fact the most simple way to implement the change. I think I will make the adaptions end of the week. Is there any way to revoke or discard my current commits?

**Comment by PF4Public** [comment]
> There's nothing to apologize for. My guess is that most contributors invest their spare time here. So I'm happy that you care for this plugin; response time is really unimportant.

Glad to hear

> Is there any way to revoke or discard my current commits?

Normally it is done via history editing and force-pushing. But if it sounds complicated or unusual to you, you can just add more commits, I'll squash them all into a single commit upon merging. No problems here.

**Comment by hoewer** [comment]
I updated my draft as discussed.

**Comment by PF4Public** [comment]
Could you please make it so that there would be only one sql query, which is chosen based on mda emptiness. Otherwise the error check that follows is checking only the last query issued.

**Comment by PF4Public** [comment]
Thank you very much! I'll do some testing on my roundcube instance and do the version-bump.

**Pull request merged**
