### PR TITLE
changed german translation

### LINKED ISSUE #9: German localization review
Anyone fluent in German please review German localization

### PR DESCRIPTION
**Pull request by internethering**
should fix #9

### CODE REVIEW

**Comment by PF4Public** [comment]
I have `.gitignote` consisting of '/.*' which prevents it itself from entering the repo as well as other dot- files and folders.
Thus I'd prefer separate pull request solely for localizations.

**Comment by internethering** [comment]
done

**Comment by PF4Public** [comment]
Did you intentionally skip 'fetchmaildelete' and 'fetchmail_to'?
BTW you can rewrite/squash your commits into one clean commit with [git rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) and force-push to your fork, which will automatically appear here. I believe 5 commits, 4 of which cancel each other, is a bad idea to merge for a single file edit. Otherwise I can cherry-pick commit 7186cca, but that's more involving for me and might remove credit from yours commit. The last one - I'm not certain, but that's possible.

**Comment by PF4Public** [comment]
Also you changed "nofetch" to not start with capital letter, why?

**Comment by PF4Public** [comment]
Closing for no reply.

**Pull request closed without merging**
