### PR TITLE
Allow use a different/existing database for fetchmail & rework to fit elastic skin settings

### LINKED ISSUE #5: fetchmail.php should validate the insertion, it returns only a "sucessfully saved"
As suggested by @internethering

In fact many calls are crying for error-checking

### PR DESCRIPTION
**Pull request by hotroot**
In this Pull Request there are two major changes:
1. I've added the possibility to use an existing fetchmail-table located outside the Roundcube Database e.g. in an existing PostfixAdmin-Database. This allows my users to manage their fetchmail settings directly from Roundcube without signing in to Postfixadmin.
2. I've reworked the plugin to fit the elasitc skin settings layout. The current version of the plugin does not work on mobile devices and the dialog does not look really nice:
fetchmail-before)
This is how it looks now: 
fetchmail-after
As you can see the list of configured accounts has moved to the sections column. For the fetchmail limit I've implemented a view in the bottom of the section column similar to the quota view in the folder preference view. 

Additionally adding and removing fetchmail accounts does no longer trigger a full page reload. the section list is updated dynamically.

### CODE REVIEW

**Comment by PF4Public** [comment]
Wow! That's a lot of changes! I honestly tried to adapt to elastic skin several times in the past years and every time failed. Awesome that you managed to make it work!

It would be great if you could mention `fetchmail_db_dsnr` within the ["Settings" section of the README](https://github.com/PF4Public/fetchmail#settings).

What was the reason for renaming the label of the plugin (`$labels['fetchmail']`)?

**Comment by hotroot** [comment]
I've added the `$config['fetchmail_db_dsnr']` to the README and adjusted the comment in `config.inc.php.dist`

The reason for renaming the label was that "Fetchmail" is not obvious for an average user in my opinion, because it's a product name and not a function or feature. At least the German translation "E-Mail Abruf" from PostfixAdmin is more intuitive for users in my oppinion, so I copied the String for all Langunage Files from PostfixAdmin translations.

**Comment by PF4Public** [comment]
OK. Please give me some time (closer to the weekend) to test your changes before merging.

**Comment by hotroot** [comment]
just found out that I cleaned up too much before commiting... now the save-button gets enabled correctly...

**Comment by PF4Public** [comment]
Please check if the default setting `$config['fetchmail_db_dsnr'] = $config['db_dsnw'];` is correct. I get following error if putting complete tree from this PR to a functioning roundcube instance and navigating to `/?_task=settings&_action=plugin.fetchmail`:
```
SERVICE CURRENTLY NOT AVAILABLE!
Error No. [600]
```
With following in roundcube logs:
```
DB Error: Configuration error. Unsupported database driver:  in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 85 (GET /?_task=settings&_action=plugin.fetchmail)
```

Also I feel uneasy with the fact that a user can invoke DNS resolution. I would suggest hiding this functionality behind a setting, which is disabled by default, so that a server admin could allow or disallow such a behaviour. I imagine this check could easily be implemented in `fetchmail.php`  <s>indem</s> in a way that `_check_server()` always returns true without checking if server setting disables the check. This allows for the least amount of modifications.

**Comment by hotroot** [comment]
I've changed the default and made the DNS check optional.

**Comment by PF4Public** [comment]
Excellent! Looks good now.

One last thing. I guess, you're using MySQL. Please check that instead of "1" you could use "true" instead:
```php
$sql = "INSERT INTO fetchmail (mailbox, domain, active, src_server, src_user, src_password, src_folder, poll_time, fetchall, keep, protocol, usessl, sslcertck, src_auth, mda) VALUES ('$mailbox', '$mailbox_domain', '$enabled', '$server', '$user', '$pass', '$folder', '$pollinterval', '$fetchall', '$keep', '$protocol', '$usessl', true, 'password', '$mda' )";
```

I'm using PostgreSQL and it seems that PHP supplies this field as an integer instead of a boolean, which it does not like.

I can fix this myself (as I still need to introduce new column in SQL schema), just need a confirmation that "true" works for you.

**Comment by hotroot** [comment]
Yes, works.

**Comment by PF4Public** [comment]
@hotroot Thank you very much. I'll need to add SQL schemes and new screenshot before publishing new release.

**Pull request merged**
