### PR TITLE
Add server port

### PR DESCRIPTION
**Pull request by semhoun**
New version of fetchmail.pl need a server port (https://github.com/postfixadmin/postfixadmin/commit/594a847dcabc8c2d3e9b775f829df9763fbf776a)

### CODE REVIEW

**Comment by PF4Public** [comment]
Given that it is a required field, should it have a default value then? Could this change break existing installations?

Please also change the commit hash of `fetchmail.pl` in the readme.

**Comment by semhoun** [comment]
> Given that it is a required field, should it have a default value then?
I'll try to add a port, and change it depending if is POP or IMAP
>  Could this change break existing installations?
If I add a defaut value in the SQL script: NO (so I have to add a default value)
Existing installation, with old fetchmail.pl will simply not use this new column.

**Comment by PF4Public** [comment]
I don't quite understand your changes for `$("#fetchmail_folder_display").show();`. You remove it, but I don't see where you restore this functionality. It is supposed to hide `folder` since it makes sense only for IMAP.

**Comment by semhoun** [comment]
I'm sorry it's stupid copy/paste mistake

**Comment by PF4Public** [comment]
Thanks!

**Pull request merged**
